version: "3"

services:
  back-end:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    ports:
      - 9000:9000
    command:
      python /code/src/main.py
    volumes:
      - ./back-end:/code
